### ISSUE TITLE
问题请教，我的项目跑起来后有如下的错误信息，请问一下是什么原因

### ISSUE THREAD

**Issue by 18945168** [caozihao/web-react-tradeview#1]
js:601 putToCacheNewBar: time violation, previous bar time: 2018-04-03T10:43:17.000Z should be less or equal to new time: 2018-04-03T10:42:19.000Z

**Comment by caozihao** [comment]
注意！这是数据问题！请务必将数据的时间限制在表单时间内（from 和 to）！

**Comment by 0x1af2aec8f957** [comment]
1、注意检查你的`DataFeed`对象中的`getBars`方法，该方法含有有onHistoryCallback回调方法，你在调用该方法设置历史数据后不可再次调用`subscribeBars`中的`onRealtimeCallback`方法，这将导致复（重）写。
2、在调用图表`setVisibleRange`方法时，range参数中的from和to为秒级时间戳，不能设置为未来的时间，且from参数应当小于to参数。

**Comment by 18945168** [comment]
谢谢
